coverage:
  range: 25..75
  round: down
  precision: 2
  notify:
    slack:
      url: "https://hooks.slack.com/services/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"
      threshold: 2%  # allow coverage to drop by 2% without posting a notification

codecov:
  branch: dev
