codecov:
  branch: gb_postgres

coverage:
  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        # threshold: 1%  # allow coverage to drop by 1% without posting a notification
        branches: null
        flags: null
        paths: null
