build:
    nodes:
        talentcloud:
            dependencies:
                before:
                    - npm rebuild
                    - npm install
                    - sudo make gen-certs
                    - sudo docker-compose up --abort-on-container-exit
                    - sudo make docker-start
                    - sudo cp -a .env.example .env
                    - sudo make build-db
                    - sudo docker-compose down -v

            root_path: './'

            environment:
                variables:
                    DB_HOST: "talentcloud-db"
                    DB_PORT: "5433"
                # Languages
                php:
                    version: "7.2"
                    ini:
                        memory_limit: "-1"
                ruby: "2.3.1"
                node: "v6.2.0"
                # Various pre-installed services that can be configured.
                docker: true
                postgresql: true
                selenium: true

        analysis:
            tests:
                override:
                    - php-scrutinizer-run --enable-security-analysis
                    - js-scrutinizer-run
                    - phpcs-run ./app ./public

filter:
    excluded_paths:
        - '*/database/*'
        - '*/node_modules/*'
        - '*/tests/*'
        - '*/vendor/*'

checks:
    php: true

tools:
    external_code_coverage:
        timeout: 777
        runs: 2
