build:
    resources:
        cpus: 1

    environment:
        variables:
            DB_HOST: 'talentcloud-db'
            DB_PORT: '5433'
        hosts:
            local.dev: 127.0.0.1
        # Languages
        php:
            version: "7.2"
            ini:
                memory_limit: "-1"
        ruby: "2.3.1"
        node: "v6.2.0"
        # Various pre-installed services that can be configured.
        docker: true
        postgresql: true
        selenium: true

    dependencies:
        override:
            - true
        before:
            - npm install
            - sudo make gen-certs
            - sudo docker-compose up --abort-on-container-exit
            - sudo make docker-start
            - sudo make build-db
            # sudo docker-compose down -v

    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run # --enable-security-analysis
                    - js-scrutinizer-run
                    - csslint-run ./public/css
                    - phpcs-run ./app
                    - phpcs-run ./public

    deployment:
        -
            commands:
                - git config --global user.email "grant.d.barnes@gmail.com"
                - git config --global user.name "Grant Barnes"
                # heroku create gc-talentcloud-s
                - heroku git:remote -a gc-talentcloud
                - git init
                - git add -A
                - git commit -m "commit for deploy to heroku"
                - git push -f heroku

filter:
    excluded_paths:
        - '*/database/*'
        - '*/node_modules/*'
        - '*/tests/*'
        - '*/vendor/*'

checks:
    javascript: true
    php: true

tools:
    external_code_coverage:
        timeout: 777
        runs: 2
