build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
                    - js-scrutinizer-run
                    - phpcs-run ./app

    # Defines the root path for your project, defaulting to the repository root directory.
    root_path: './'

    environment:
        # Any valid timezone identifier
        # see TZ column on https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        timezone: UTC

        # Sets up DNS entries for certain hosts
        hosts:
            local.dev: 127.0.0.1

        # Languages
        php:
            version: "7.2"
            ini:
                memory_limit: "-1"

        ruby: "2.3.1"
        node: "v6.2.0"

        # Various pre-installed services that can be configured.
        docker: true
            #logins:
            # { username: "user", password: "s3cret", server: "docker.io" }
            # # more logins

            #cache:
            #    images:
            #    - "scrutinizer/web:tag-name"
            #    - "scrutinizer/*"

        postgresql:           true
        nginx:
            sites:
                # will add configuration file to "/etc/nginx/sites-enabled"
                talentcloud:
                    host: 'local.dev'
                    #web_root: 'web/'

                    # These are optional and usually do not require changing.
                    index: 'index.php index.html'

                    locations:
                        - >
                           location ~ [^/]\.php(/|$) {
                               try_files $uri $uri/ /index.php /index.html;
                               fastcgi_index index.php;
                               fastcgi_split_path_info ^(.+?\.php)(/.*)$;
                               fastcgi_pass 127.0.0.1:9000;
                               include fastcgi_params;
                           }

        selenium:
            version:                2.53
            chrome_driver_version:  2.22
            # browser_name:           ~     # can also be set from your tests

    commands:
        - composer self-update

filter:
    excluded_paths:
        - '*/data/*'
        - '*/node_modules/*'
        - '*/tests/*'
        - '*/vendor/*'

checks:
    php:
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true

tools:
    external_code_coverage:
        timeout: 777
        runs: 2
    js_hint:
        filter:
            excluded_paths: ['*/tests/*','*/vendor/*','*/node_modules/*','*/data/*']
    php_mess_detector:
        filter:
            excluded_paths: ['*/tests/*','*/vendor/*','*/node_modules/*','*/data/*']
    sensiolabs_security_checker: true
    php_pdepend:
        excluded_dirs:
            - tests
            - vendor
            - data
            - node_modules

    php_hhvm: true
    # PHP Similarity Analyzer and Copy/paste Detector cannot be used at
    # the same time right now. Make sure to either remove, or disable one.
    php_sim: false
    php_cpd: true
