build:
  nodes:
    docker-build:
      environment:
        # caching works with the remote_engine and the local executor
        php:
          version: 5.6
        hosts:
          local.dev: $DOCKER_IP
        docker: true

#    tests:
#      override:
#        -
#          command: 'vendor/bin/phpunit --coverage-clover=coverage.clover'
#          coverage:
#            file: 'coverage.clover'
#            format: 'clover'

filter:
  excluded_paths:
        - '*/data/*'
        - '*/node_modules/*'
        - '*/tests/*'
        - '*/vendor/*'

checks:
  php:
    remove_extra_empty_lines: true
    remove_php_closing_tag: true
    remove_trailing_whitespace: true
    fix_use_statements:
      remove_unused: true
      preserve_multiple: false
      preserve_blanklines: true
      order_alphabetically: true
    fix_php_opening_tag: true
    fix_linefeed: true
    fix_line_ending: true
    fix_identation_4spaces: true
    fix_doc_comments: true

tools:
  external_code_coverage: false
  js_hint:
    filter:
      excluded_paths: ['*/tests/*','*/vendor/*','*/node_modules/*','*/data/*']
  php_mess_detector:
    filter:
      excluded_paths: ['*/tests/*','*/vendor/*','*/node_modules/*','*/data/*']
    sensiolabs_security_checker: true
    php_pdepend:
      excluded_dirs:
        - tests
        - vendor
        - data
        - node_modules

#  external_code_coverage:
#    timeout: '777'
#    runs: 2

    php_hhvm: true
    # PHP Similarity Analyzer and Copy/paste Detector cannot be used at
    # the same time right now. Make sure to either remove, or disable one.
    php_sim: true
    php_cpd: false
