# Talent Cloud
# .scrutinizer.yml

build:
    environment:
        php:
            version: 5.6

    tests:
        command: 'vendor/bin/phpunit --coverage-clover=coverage.clover'
        coverage:
            file: 'coverage'
            format: 'clover'

filter:
    excluded_paths:
        - '*/tests/*'
        - '*/vendor/*'

tools:
    external_code_coverage: true
    js_hint:
        filter:
            excluded_paths: ['*/tests/*','*/vendor/*']
    php_mess_detector:
        filter:
            excluded_paths: ['*/tests/*','*/vendor/*']
    sensiolabs_security_checker: true
    php_pdepend:
        excluded_dirs:
            - tests
            - vendor
    external_code_coverage:
        timeout: '777'
    php_hhmv: true

    # PHP Similarity Analyzer and Copy/paste Detector cannot be used at
    # the same time right now. Make sure to either remove, or disable one.

    php_sim: false
    php_cpd: true
