# Talent Cloud
# .scrutinizer.yml

build:
    environment:
        php:
            version: 5.6
        docker: true
        hosts:
            local.dev: '127.0.0.1'

        apache2:
            modules: ['rewrite']
            sites:
                symfony_app:
                    web_root: 'public_html/'
                    host: 'local.dev'
                    rules:
                        - 'RewriteCond %{HTTP_REFERER} !^$'
                        - 'RewriteCond %{HTTP_REFERER} !^http://(tc.)?gccollab.ca/ [NC]'
                        - 'RewriteRule .(gif|jpg|png)$ - [F]'

#    tests:
#      override:
#        -
#          command: 'vendor/bin/phpunit --coverage-clover=coverage.clover'
#          coverage:
#            file: 'coverage.clover'
#            format: 'clover'

filter:
    excluded_paths:
        - '*/tests/*'
        - '*/vendor/*'

checks:
    php:
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true

tools:
    external_code_coverage: false
    js_hint:
        filter:
            excluded_paths: ['*/tests/*','*/vendor/*']
    php_mess_detector:
        filter:
            excluded_paths: ['*/tests/*','*/vendor/*']
    sensiolabs_security_checker: true
    php_pdepend:
        excluded_dirs:
            - tests
            - vendor

#  external_code_coverage:
#      timeout: '777'
#      runs: 2

    php_hhvm: true
    # PHP Similarity Analyzer and Copy/paste Detector cannot be used at
    # the same time right now. Make sure to either remove, or disable one.
    php_sim: false
    php_cpd: true
