build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run --enable-security-analysis
                    - js-scrutinizer-run
                    - phpcs-run

    dependencies:
        before:
            - composer install
            - make gen-certs
            - docker-compose up
            - make build-db
            - make test
            - psql --cluster 9.4/main -c 'CREATE DATABASE talentcloud WITH OWNER scrutinizer'

    root_path: './'

    environment:
        variables:
            # DB_HOST: 'localhost'
            DB_PORT: '5432'
            DB_DATABASE: 'talentcloud'
            DB_USERNAME: 'scrutinizer'
            DB_PASSWORD: 'scrutinizer'
        # Languages
        php:
            version: "7.2"
            ini:
                memory_limit: "-1"
        ruby: "2.3.1"
        node: "v6.2.0"
        # Various pre-installed services that can be configured.
        docker: true
        postgresql: "9.4"
        selenium: true

filter:
    excluded_paths:
        - '*/database/*'
        - '*/node_modules/*'
        - '*/tests/*'
        - '*/vendor/*'

checks:
    php: true

tools:
    external_code_coverage:
        timeout: 777
        runs: 2
    custom_commands:
        -
            scope: project
            command: vendor/bin/slack --token=https://hooks.slack.com/services/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
