# Talent Cloud
# .scrutinizer.yml

build:
    environment:
        php:
            version: 5.6

nodes:
    analysis:
        dependencies:
            after:
             - composer require --dev squizlabs/php_codesniffer:2.9

    tests:
        override:
            command: phpcs-run
            use_website_config: false

filter:
    excluded_paths:
        - '*/tests/*'
        - '*/vendor/*'

tools:
    external_code_coverage: true
    js_hint:
        filter:
            excluded_paths: ['*/tests/*','*/vendor/*']
    php_mess_detector:
        filter:
            excluded_paths: ['*/tests/*','*/vendor/*']
    sensiolabs_security_checker: true
    php_pdepend:
        excluded_dirs:
            - tests
            - vendor
    external_code_coverage:
        timeout: '777'
    php_hhvm: true

    # PHP Similarity Analyzer and Copy/paste Detector cannot be used at
    # the same time right now. Make sure to either remove, or disable one.
    php_sim: true
    php_cpd: false
