# Talent Cloud
# .travis.yml

language: php
php:
 - 5.6
 - 5.5

sudo: false

matrix:
  allow_failures:
    - php: 5.5

services:
 - mysql

# before_script:

install:
 - composer self-update
 - composer install

script:
 - composer validate

# after_script:
