# language:
#   - php

sudo: required

env-docker:
  DOCKER_COMPOSE_VERSION: 1.18.0

services:
  - docker

before_install:
  - sudo apt update
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-`uname -m` > ./docker-compose
  - sudo mv ./docker-compose /usr/bin/docker-compose
  - sudo chmod +x /usr/bin/docker-compose
  - docker-compose ps -q | xargs docker inspect -f '{{ .State.ExitCode }}' | grep -v 0 | wc -l | tr -d ' '

before_script:
  - sudo make docker-start
  - sleep 2m

script:
  - sudo make apidoc
  - sudo make gen-certs
  - sudo make mysql-dump
  - sudo make mysql-restore
  # sudo make phpmd
  # sudo make test

after_script:
  - docker build -t gggrant/tc-laravel:travis
  - sudo make docker-stop
