# language:
#   - php

sudo: required

env-docker:
  DOCKER_COMPOSE_VERSION: 1.18.0

services:
  - docker

before_install:
  - sudo apt update
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-`uname -m` > ./docker-compose
  - curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
  - sudo mv ./docker-compose /usr/bin/docker-compose
  - sudo chmod +x /usr/bin/docker-compose
  - docker-compose ps -q | xargs docker inspect -f '{{ .State.ExitCode }}' | grep -v 0 | wc -l | tr -d ' '

before_script:
  - sudo make docker-start
  - sleep 2m
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
  - sudo npm install

script:
  - sudo make gen-certs
  - sudo make mysql-dump
  - sudo make mysql-restore
  # sudo make phpmd
  # sudo make test
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_script:
  - docker build -t gggrant/tc-laravel-travis
  - sudo make docker-stop

# do not send emails
notifications:
    email: never
