# Talent Cloud
# .travis.yml

language: php
php:
 - 5.6
 - 5.5

sudo: false

matrix:
  allow_failures:
    - php: 5.5

services:
 - mysql

before_script:
 # composer require atoum/atoum

install:
 - composer update
 - composer install

script:
 - composer validate
 - mkdir -p build/logs
 # phpunit --coverage-clover build/logs/clover.xml
