version: '2'
services:
    # Nginx Web Server
    nginx:
        image: nginx:alpine
        container_name: nginx
        working_dir: /var/www
        volumes_from:
            - talentcloud
        restart: always
        depends_on:
            - talentcloud
            - talentcloud-db
        volumes:
            - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
            - "./:/var/www"
        environment:
            - "NGINX_HOST=tc.gccollab.ca"
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        ports:
            - "80:80"
            - "443:443"
    # Application / PHP-FPM
    talentcloud:
        build: .
        # image: gctcntgc/talentcloud:dev_refactor
        container_name: talentcloud
        working_dir: /var/www
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./:/var/www"
        links:
            - talentcloud-db
        environment:
            - "DB_PORT=5432"
            - "DB_HOST=talentcloud-db"
    # Database
    talentcloud-db:
        image: postgres
        container_name: talentcloud-db
        restart: always
        volumes:
            - "./database/db/postgresql/data:/var/lib/postgresql/data"
            # "./database/db/dumps:/docker-entrypoint-initdb.d"
        environment:
            # "POSTGRES_DB=talentcloud"
            # "POSTGRES_USER=talentcloud"
            - "POSTGRES_PASSWORD=talentcloud"
            - "PGDATA=/database/db/postgresql/data/pgdata"
        ports:
            - "5433:5432"
    # Postgres Admin
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        restart: always
        links:
            - talentcloud-db
        environment:
            - "PGADMIN_DEFAULT_EMAIL=grant.d.barnes@gmail.com"
            - "PGADMIN_DEFAULT_PASSWORD=talentcloud"
        ports:
            - "8888:80"
    # Composer
    composer:
        image: "composer"
        container_name: composer
        volumes:
            - "./:/app"
        command:
            - install
