version: '2'
services:
    # Nginx Web Server
    nginx:
        image: nginx:alpine
        container_name: nginx
        working_dir: /var/www
        volumes_from:
            - talentcloud
        restart: always
        depends_on:
            - talentcloud
            - talentcloud-db
        volumes:
            - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
            - "./:/var/www"
        environment:
            - "NGINX_HOST=tc.gccollab.ca"
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        ports:
            - "80:80"
            - "443:443"
    # Application / PHP-FPM
    talentcloud:
        build: .
        # image: gctcntgc/talentcloud:dev_refactor
        container_name: talentcloud
        working_dir: /var/www
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./:/var/www"
    # Database
    talentcloud-db:
        image: mysql:5.6
        container_name: talentcloud-db
        restart: always
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
            - "./data/db/dumps:/docker-entrypoint-initdb.d"
        environment:
            - "MYSQL_DATABASE=talentcloud"
            - "MYSQL_ROOT_PASSWORD=talentcloud"
            - "MYSQL_USER=talentcloud"
            - "MYSQL_PASSWORD=talentcloud"
        ports:
            - "33061:3306"
    # PHP MyAdmin
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        links:
            - talentcloud-db
        environment:
            - "PMA_ARBITRARY=1"
            - "PMA_HOST=talentcloud-db"
        ports:
            - "8080:80"
    # Composer
    composer:
        image: "composer"
        volumes:
            - "./:/app"
        command: 
            - install
