version: '2'
services:
  # ###########################################################################
  # The Talent Cloud container. Accessible at http://localhost:8080
  # ###########################################################################
  talentcloud:
    build: .
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
      - ./data/data:/data
      - /var/www/html/vendor
      - /var/www/html/docker
    depends_on:
      - talentcloud-db
      # nginx-proxy
    environment:
      - VIRTUAL_HOST=tc.gccollab.ca
      - DOCKER=1
      - HOME=/var/www/html
      - DBHOST=talentcloud-db
      - WWWROOT=http://tc.gccollab.ca/

  talentcloud-db:
    image: library/mysql:5.6
    environment:
      - MYSQL_DATABASE=talentcloud
      - MYSQL_USER=talentcloud
      - MYSQL_PASSWORD=Canada123!@#
      - MYSQL_ROOT_PASSWORD=Canada123!@#
    volumes:
      # ./dump:/docker-entrypoint-initdb.d
      # persistent:/var/lib/mysql
      - ./dump:/var/lib/mysql
