# TalentCloud
# docker-compose.yml

version: '3'
services:

    composer:
        image: "composer"
        container_name: composer
        volumes:
            - "./web/app:/app"
        command:
            - self-update
            - install

    nginx:
        image: nginx:alpine
        container_name: nginx
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
            # "./web:/var/www/html"
            - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - php-fpm
            - mysql
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        networks:
          - bridge

    php-fpm:
        image: nanoninja/php-fpm:${PHP_VERSION}
        container_name: php-fpm
        restart: always
        networks:
          - bridge
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./web:/var/www/html"

    mysql:
        image: mysql:${MYSQL_VERSION}
        container_name: mysql
        restart: always
        networks:
          - bridge
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
            - "./data/db/dumps:/docker-entrypoint-initdb.d"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8080:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${MYSQL_HOST}
        restart: always
        links:
            - mysql

networks:
    bridge:
