version: '2'
services:
  # ###########################################################################
  # The Talent Cloud container. Accessible at http://tc.gccollab.ca
  # ###########################################################################
  talentcloud:
    build: .
    ports:
      - 80:80
    volumes:
      - ./public_html:/var/www/html
      - ./data:/data
      - /public_html/vendor
      - /public_html/docker
      - /public_html/install
    depends_on:
      - talentcloud-db
      # nginx-proxy
    environment:
      - VIRTUAL_HOST=tc.gccollab.ca
      - DOCKER=1
      - HOME=/public_html
      - DBHOST=talentcloud-db
      - WWWROOT=http://tc.gccollab.ca

  talentcloud-db:
    image: library/mysql:5.6
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=talentcloud
      - MYSQL_USER=talentcloud
      - MYSQL_PASSWORD=Canada123!@#
      - MYSQL_ROOT_PASSWORD=Canada123!@#
